CREATE TABLE IF NOT EXISTS audit_vault (
    id BIGSERIAL PRIMARY KEY,
    previous_hash TEXT, -- The hash of the record immediately before this one
    current_hash TEXT NOT NULL, -- SHA-256 of (id + action + timestamp + previous_hash)
    actor_bsuid TEXT NOT NULL, -- Business User ID (from WhatsApp/Teams)
    action_type TEXT NOT NULL, -- e.g., 'JIRA_CREATE', 'GATEWAY_APPROVAL'
    payload JSONB NOT NULL,
    reasoning_trace JSONB, -- The ReAct "thought" process behind the action
    created_at TIMESTAMPTZ DEFAULT now() NOT NULL
);

-- Force the table to be append-only via a Postgres Rule
CREATE RULE protect_audit_log AS ON UPDATE TO audit_vault DO INSTEAD NOTHING;
CREATE RULE prevent_delete_audit AS ON DELETE TO audit_vault DO INSTEAD NOTHING;

-- Note: In production, the current_hash is generated by the 
-- src/lib/security/hash-chain.ts logic before insertion to ensure 
-- application-level integrity.